CREATE TABLE [dbo].[Table]
(
	[OGRID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [OGRAD] VARCHAR(50) NULL, 
    [OGRSOYAD] VARCHAR(50) NULL, 
    [OGRMAIL] VARCHAR(100) NULL, 
    [OGRFOTO] VARCHAR(500) NULL, 
    [OGRADRES] VARCHAR(100) NULL
)
